- name: Demo on Conditions
  hosts: all
  connection: local
  vars:
    fruit: false
    vegetable: false
  tasks:
    - name: Print Fruit Names
      ansible.builtin.debug:
        msg: Fruits name - Apple, Mango
      when: fruit is true

    - name: Print Vegetable Names
      ansible.builtin.debug:
        msg: Vegetables name - Carrot
      when: vegetable is true