- name: Demo for AWS Parameter Store
  hosts: localhost
  connection: local
  tasks:
    - name: Fetch some value
      ansible.builtin.debug:
        msg: "{{ lookup('amazon.aws.aws_ssm', 'docdb.dev.database_name', region = 'us-east-1')}}"