- name: Template Demo
  hosts: localhost
  connection: local
  vars:
    fruit_name: apple
  tasks:
    - name: Create Template
      ansible.builtin.template:
        src: test.txt
        dest: /tmp/test.txt

#HashiCorp Vault - Manage Secrets and Protect Sensitive Data
#HashiCorp Consul - Identity based networking
#AWS Systems Manager Parameter Store - Secrets and Configuration Management
