- name: Variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Print Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
## Ansible access variables with two flower brackets
    - name: Print Task Variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.google.com